### ISSUE TITLE
LightSail Launch Script 문제

### ISSUE THREAD

**Issue by rapanui** [subicura/workshop-init#1]
AWS LightSail 에서 인스턴스 생성시에 입력하는 Lauch Script 를 안내해주신 내용으로 넣으면, 이후 인스턴스 생성완료후에 적용이 안되네요.

처음 환경 세팅시에 문제라서 이후 과정 따라가기가 안되요;; ㅠㅠ

**Comment by seongilp** [comment]
npm 실행 시 sudo를 붙이고 해보세요

**Comment by subicura** [comment]
launch script를 수정하였습니다~
