### ISSUE TITLE
무작위 대입공격에 ssh 로긴이 뚫렸었습니다

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [subicura/workshop-init#3]
안녕하세요 :) 먼저 좋은 솔루션 공유해 주셔서 감사합니다.

두달 전 쯤, 이 repo 를 참고하여 Lightsail 을 사용하다 깜빡잊고 방치한 인스턴스가 있었습니다.
일주일뒤? AWS 로 부터의 메일을 한통 받았는데,
그 방치해 두었던 Lightsail 이 다른 머신에 공격시도를 하고 있다는 메일이었고,
확인해보니 공격자가 Lightsail 인스턴스에 무작위 대입공격을 시도, 15분 만에 ssh 로 로긴을 성공했고,
인스턴스 안에서 모네로 채굴과 아마도 같은 방식으로 또 다른 머신을 공격 시도 했던 것이 확인되었습니다.
다행히 해당 인스턴스 안에 아무것도 없어서 직접적인 피해는 없었지만 :)
혹여 다른 피해자가 발생 할 수 있으니,

**현재 쉬운 비번 `1q2w3e4r`  을 좀 더 어렵게 바꿔 놓으면 어떨까요?**
아니면 유저가 직접 어려운 비번으로 입력할 수 있게 가이드를 추가해도 좋을 것 같구요!
(한번 데이고 나니 확실히 겁이 많아졌습니다ㅎㅎ)

**Comment by subicura** [comment]
안녕하세요! 잠깐 실습하기 위한 용도로 비번을 쉽게 설정했는데 그런 이슈가 있었군요. 비번 수정 가이드를 추가하겠습니다. 감사합니다.
